stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: infoubicatecl/helloworld:latest
      pushRemote: true
      registry: index.docker.io
branch:
  include:
  - master
notification: {}
